// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UrnaEletronicaWebAPI.Models;

namespace UrnaEletronicaWebAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220727134812_FirstMigration")]
    partial class FirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0");

            modelBuilder.Entity("UrnaEletronicaWebAPI.Models.Candidate", b =>
                {
                    b.Property<int>("Legenda")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataRegistro")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeVice")
                        .HasColumnType("TEXT");

                    b.HasKey("Legenda");

                    b.ToTable("Candidates");

                    b.HasData(
                        new
                        {
                            Legenda = 10,
                            DataRegistro = new DateTime(2022, 7, 27, 10, 48, 11, 925, DateTimeKind.Local).AddTicks(944),
                            Nome = "Leonardo Macedo",
                            NomeVice = "Felipe Cardoso"
                        },
                        new
                        {
                            Legenda = 15,
                            DataRegistro = new DateTime(2022, 7, 27, 10, 48, 11, 926, DateTimeKind.Local).AddTicks(2999),
                            Nome = "Paula Machado",
                            NomeVice = "Maria Souza"
                        },
                        new
                        {
                            Legenda = 19,
                            DataRegistro = new DateTime(2022, 7, 27, 10, 48, 11, 926, DateTimeKind.Local).AddTicks(3018),
                            Nome = "Diego Oliveira",
                            NomeVice = "Arnildo Silva"
                        },
                        new
                        {
                            Legenda = 18,
                            DataRegistro = new DateTime(2022, 7, 27, 10, 48, 11, 926, DateTimeKind.Local).AddTicks(3023),
                            Nome = "Marcia Fernandes",
                            NomeVice = "Camila Ferreira"
                        },
                        new
                        {
                            Legenda = 32,
                            DataRegistro = new DateTime(2022, 7, 27, 10, 48, 11, 926, DateTimeKind.Local).AddTicks(3023),
                            Nome = "João Campos",
                            NomeVice = "César Oliveira"
                        },
                        new
                        {
                            Legenda = 45,
                            DataRegistro = new DateTime(2022, 7, 27, 10, 48, 11, 926, DateTimeKind.Local).AddTicks(3032),
                            Nome = "Fernanda Pinheiro",
                            NomeVice = "Maurício Mendes"
                        });
                });

            modelBuilder.Entity("UrnaEletronicaWebAPI.Models.Vote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataVoto")
                        .HasColumnType("TEXT");

                    b.Property<int?>("LegendaCandidato")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Votes");
                });
#pragma warning restore 612, 618
        }
    }
}
