// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UrnaEletronica.Data;

namespace UrnaEletronica.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220722020748_InitialCreation")]
    partial class InitialCreation
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("UrnaEletronica.Models.Candidate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("DataRegistro")
                        .HasColumnType("TEXT")
                        .HasColumnName("data_registro");

                    b.Property<int>("Legenda")
                        .HasColumnType("INTEGER")
                        .HasColumnName("legenda");

                    b.Property<string>("NomeCanditato")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("nome_canditato");

                    b.Property<string>("NomeVice")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("nome_vice");

                    b.Property<int>("QuantidadeVotos")
                        .HasColumnType("INTEGER")
                        .HasColumnName("quantidade_votos");

                    b.HasKey("Id")
                        .HasName("pk_candidate");

                    b.ToTable("candidate");
                });

            modelBuilder.Entity("UrnaEletronica.Models.Vote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("CandidateId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("candidate_id");

                    b.Property<DateTime>("DataVoto")
                        .HasColumnType("TEXT")
                        .HasColumnName("data_voto");

                    b.HasKey("Id")
                        .HasName("pk_vote");

                    b.HasIndex("CandidateId")
                        .IsUnique();

                    b.ToTable("vote");
                });

            modelBuilder.Entity("UrnaEletronica.Models.Vote", b =>
                {
                    b.HasOne("UrnaEletronica.Models.Candidate", "Candidate")
                        .WithOne("Vote")
                        .HasForeignKey("UrnaEletronica.Models.Vote", "CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidate");
                });

            modelBuilder.Entity("UrnaEletronica.Models.Candidate", b =>
                {
                    b.Navigation("Vote");
                });
#pragma warning restore 612, 618
        }
    }
}
